### ISSUE TITLE
error when running wdio

### ISSUE THREAD

**Issue by vibdev** [stsvilik/wdio-docker-service#19]
when I try and run my wdio tests with this service I am getting:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Couldn't initialise launcher from service "docker".
Error: Cannot find module './lib/launcher'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/node_modules/wdio-docker-service/launcher.js:2:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Launcher.getLauncher (~/node_modules/webdriverio/build/lib/launcher.js:731:35)
    at Launcher._callee$ (~/node_modules/webdriverio/build/lib/launcher.js:233:49)
    at tryCatch (~/code/muse/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (~/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at !/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (!/node_modules/core-js/library/modules/_export.js:35:28)
    at Launcher.<anonymous> (~/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Launcher.run (~/node_modules/webdriverio/build/lib/launcher.js:373:29)
```

**Comment by stsvilik** [comment]
Looking into it

**Comment by stsvilik** [comment]
Please update package to version 1.1.5 this should fix it. I messed up prepublish config :)
