### ISSUE TITLE
ERROR: connect ECONNREFUSED 127.0.0.1:4444

### ISSUE THREAD

**Issue by prianchiru** [stsvilik/wdio-docker-service#23]
Configured the config file as mentioned in the example. I am getting this error on building the image. my configuration files are as follows.

```js
// wdio.conf.js
exports.config = {
  // ...
  specs: [

    // 'specs/login.spec.js',
    // 'specs/medical_codes.spec.js',
    'test2.js'  
    // 'specs/chart_view.spec.js'
],
  services: ['docker'],
//   mochaOpts: {
//     timeout: 9999999,
//     ui: 'bdd',
// },
  // ...
  // Options are set here as well
  capabilities: [{
    maxInstances: 5,
    browserName: 'firefox',
    assumeUntrustedCertIssuer: true,
    canAssumeUntrustedCertIssuer: true,
    setAcceptUntrustedCertificates: true,
    ignoreUndefinedDefinitions: true,
    acceptInsecureCerts: true,
    acceptSslCerts: true,
    trustAllSSLCertificates: true
  }],
  dockerLogs: './logs',
  dockerOptions: { 
    image: 'selenium/standalone-firefox',
    healthCheck: 'http://localhost:4444',
    options: { 
      p: ['4444: 4444'],
      shmSize: '2g'
    }    
  },
  before: function (capabilities, specs) {
    browser.timeouts('script', 5000000);
    browser.timeouts('implicit', 1000);
    browser.timeouts('page load', 5000000);
  },
  //...
};
```

Dockerfile
`FROM node:carbon
ADD . /app
WORKDIR /app
RUN npm i
RUN npm run test`

Full error text as follows
```bash
NOTE: Pulling image for the first time. Please be patient.
ERROR: connect ECONNREFUSED 127.0.0.1:4444
firefox
    at new RuntimeError (/app/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/app/node_modules/webdriverio/build/lib/utils/RequestHandler.js:327:43)
    at self.callback (/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codingserviceautomation@1.0.0 test: `wdio test.conf`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codingserviceautomation@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-02T10_11_20_106Z-debug.log
```

**Comment by stsvilik** [comment]
I'll need some help to understand whats going on here, so I'll ask you a few questions:
1. Do you have any proxies on your network that could prevent `selenium/standalone-firefox` image from being pulled off public DockerHub?
2. What is that other Dockerfile you mention?

Just to clarify things you can only deal with one docker image at a time - either use Selenium dockers to run your tests or use some other service in addition to this one to run tests against your custom docker app, but not both.

Next troubleshooting steps:
- try to pull `selenium/standalone-firefox` in your command line to see if it works.

**Comment by stsvilik** [comment]
Actually @prianchiru I think you're trying to run this within a docker container. If so then you have few choices to proceed:
a. Install docker into your testing container as dependency (kinda complex way)
b. Have another parallel container running `selenium/standalone-firefox` joined by same network. In this scenario you don't even need `docker` service, just point config to a container where selenium runs.
c. Install Firefox in your testing container and use `wdio-selenium-standalone` service with Firefox config.

**Comment by stsvilik** [comment]
@prianchiru Is this still an issue for you?

**Comment by stsvilik** [comment]
Closing due to inactivity - if you still have issues please re-open.

**Comment by rostgoat** [comment]
having issues with this using wdio v5

**Comment by stsvilik** [comment]
This version is not yet compatible with v5

**Comment by prathameshnyt** [comment]
@stsvilik it's still not compatible with v5? 

Thanks,
Prathamesh

**Comment by stsvilik** [comment]
For all looking for answers related to this issue please be advised that a) latest version is compatible with WDIO 5 and b) likely cause is not using `async/await` with `browser` methods.

**Comment by kannan2790** [comment]
> For all looking for answers related to this issue please be advised that a) latest version is compatible with WDIO 5 and b) likely cause is not using `async/await` with `browser` methods.

I am facing the same problem when i run docker service with wdio v5. You mentioned its "compatible" ?

**Comment by stsvilik** [comment]
@kannan2790 yes version 5 is supported as of 2.x

**Comment by zastqa** [comment]
I am still experiencing this issue with wdio v5 with latest wdio-docker-service
try with async/await with browser but didn't work out 
I need to use service as 'docker' with image - selenium/standalone-chrome so can you please help me on it ?

**Comment by ajitqait** [comment]
I am running protractor script using docker-compose with setup of selenium grid and calling dockerfile in docker-compose using build: .
Docker Compose File Is below:

version: '3'

services:
    progrid:
        image: selenium/hub:3.141.59-20210105
        container_name: progrid
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=240000
            - GRID_BROWSER_TIMEOUT=240000
        networks:
            - progrid_grid_internal

    nodechrome:
        image: selenium/node-chrome-debug:3.141.59-20210105
        depends_on:
            - progrid
        environment:
            - HUB_HOST=progrid
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=1
            - NODE_MAX_SESSION=2
        networks:
            - progrid_grid_internal
    first:
        build: .
        depends_on:
            - nodechrome
        environment:
            - HUB_HOST=progrid
            - BROWSER=chrome
networks:
    progrid_grid_internal:


Dockerfile:

FROM node:alpine

RUN mkdir /DLT_Labs

WORKDIR /DLT_Labs/

RUN apk update && apk add bash 
  

RUN npm install -g protractor@5.4.4
# RUN webdriver-manager update
RUN npm install
COPY ./ ./

CMD protractor proconf.js

proconf.js
exports.config = {
  framework: 'jasmine',
  capabilities: {
    'browserName': 'chrome'
  },
  seleniumAddress: 'http://progrid:4444/wd/hub',
  specs: ['spec.js']
}

spec.js:

describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');
    
    expect(browser.getTitle()).toEqual('Super Calculator');
  });
});

Error: : 
 Or ECONNREFUSED 127.0.0.0:4444 error




Please help me out for this problem.

**Comment by stsvilik** [comment]
@ajitqait sorry, but what does this example have to do with wdio dockers service?
