### ISSUE TITLE
docker event --format only available since 1.13

### ISSUE THREAD

**Issue by mouyigang** [stsvilik/wdio-docker-service#43]
After updated to 1.5.0 we start to see errors like this:
```consle
Launching docker image 'chromeheadless:66.0'
Error: Error executing sub-child: docker events --format {{json\ .}} --filter image=chromeheadless:66.0
    at DockerEventsListener._onMessage (/node_modules/wdio-docker-service/src/utils/dockerEventsListener.js:57:27)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

The docker service starts as expected though, the problem lays on the older version of docker we are using: 1.12.

Would be nice if you can update the release note so that other user will be noticed about this change.

**Comment by stsvilik** [comment]
@mouyigang Thank you for letting me know, will do.

**Comment by stsvilik** [comment]
Release notes updated
