### ISSUE TITLE
Upload local file to browser

### ISSUE THREAD

**Issue by callemang** [stsvilik/wdio-docker-service#81]
Hello, I am attempting to upload a jpg to the browser. I can console.log out the file's location but I am getting a "file no found" when running with this service. This does work when using selenium-standalone service. 

The code is similar to this:
```
it ("can create movie 1", function() {
        // Viewing local files (local to my machine or inside of the selenium container?)
        var spawn = require('child_process').spawn;
        var ls  = spawn('ls', ['/home/chris/SEER/core-qa-automation/webdriverIO/test/files/']);
        ls.stdout.on('data', function (data) {
            console.log("ls on path to files (/home/chris/SEER/core-qa-automation/webdriverIO/test/files/): " + data);
        });

        VideosPage.open();

        const filePath = path.join(__dirname, '../files/dbz.jpg');
        this.uploadFilePath.setValue(filePath);
})
```

The error logs look like this:
```
[0-0] RUNNING in chrome - /test/specs/turnkeyDemoCarousel.spec.js
[0-0] ls on path to files (/home/chris/SEER/core-qa-automation/webdriverIO/test/files/): bojack-unbound.jpg
dbz.jpg
dbz-series.jpg
one-second.mp4
return-of-cooler.jpg

[0-0] 2020-03-21T18:17:40.711Z ERROR webdriver: Request failed due to invalid argument: invalid argument: File not found : /home/chris/SEER/core-qa-automation/webdriverIO/test/files/dbz.jpg
  (Session info: chrome=80.0.3987.106)
    at getErrorFromResponseBody (/home/chris/SEER/core-qa-automation/webdriverIO/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:124:10)
    at Request._callback (/home/chris/SEER/core-qa-automation/webdriverIO/node_modules/@wdio/runner/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/chris/SEER/core-qa-automation/webdriverIO/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/home/chris/SEER/core-qa-automation/webdriverIO/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/home/chris/SEER/core-qa-automation/webdriverIO/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
[0-0] invalid argument in "SEER backend can create movie 1"
invalid argument: File not found : /home/chris/SEER/core-qa-automation/webdriverIO/test/files/dbz.jpg
  (Session info: chrome=80.0.3987.106)
[0-0] FAILED in chrome - /test/specs/turnkeyDemoCarousel.spec.js`
```

Any help would be appreciated. This project is awesome and I'd love to continue to use it.
Much thanks!

**Comment by stsvilik** [comment]
@callemang for starters Selenium stand-alone will work with local browser binary running on your machine. Docker service runs Chrome in the docker container and may have permission issues or it may not have access to the file you're trying to upload. Perhaps you need to map a directory where upload file resides into the docker container?

**Comment by callemang** [comment]
Yessir! Mounting the volumes into my selenium container (like below) worked like a charm.
```
options: {
            p: ['4444:4444'],
            v: ['/home/chris/SEER/core-qa-automation/webdriverIO/test/files:/tmp/localfiles/'],
            shmSize: '2g'
        }
```
Much appreciated. I am closing this issue.

**Comment by stsvilik** [comment]
@callemang I'm glad it all worked out :)
