### ISSUE TITLE
Getting error while running webdriver io tests on chromestandalone docker image

### ISSUE THREAD

**Issue by amartanwar42** [stsvilik/wdio-docker-service#82]
2020-04-20T17:44:07.162Z ERROR wdio-docker-service: Error: Error executing sub-child: docker events --format "{{json .}}" --filter image=selenium/standalone-chrome
     at DockerEventsListener._onMessage (/builds/get.on/patientapp-web-automation/node_modules/wdio-docker-service/lib/utils/dockerEventsListener.js:67:21)
     at ChildProcess.emit (events.js:315:20)
     at ChildProcess.EventEmitter.emit (domain.js:485:12)
     at emit (internal/child_process.js:881:12)
     at processTicksAndRejections (internal/process/task_queues.js:85:21)
 2020-04-20T17:44:07.163Z WARN wdio-docker-service: Disconnecting dockerEventsListener: 234
 Error: connect ECONNREFUSED 127.0.0.1:8080

**Comment by stsvilik** [comment]
@amartanwar42 is `docker` service running? Also what options are you setting for docker - this error means that docker command failed to execute.

**Comment by shashtrih** [comment]
I am getting simliar error using wdio-docker-service@2.3.0 over CI/CD gitlab pipelines  here its my wdio.conf.js file
can you please suggest i need to change or add anything ? 
exports.config = {
    
    suites: {
        accessibility: [
            './automation/accessibility/a11y-test.js'
        ]
    },
    maxInstances: 20,
    capabilities: [
        {browserName: 'chrome',
            'goog:chromeOptions': {
                args:  ['--disable-gpu', '--window-size=1680,1050']
                
            }

        }

    ],
    runner: 'local',
    sync: true,
    //
    // Level of logging verbosity: silent | verbose | command | data | result | error
    logLevel: 'debug',

    hostname: 'localhost',

    // Set a base URL in order to shorten url command calls. If your url parameter starts
    // with "/", then the base url gets prepended.
    baseUrl: 'http://localhost:8080',
    // Default timeout for all waitFor* commands.
    waitforTimeout: 180000,

    //
    
    //
    // Default request retries count
    connectionRetryCount: 3,

    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['docker'],
    dockerLogs: './dockerLogs',
    dockerOptions: {
        image: 'selenium/standalone-chrome:3.141.59-20200409',
        healthCheck: {
            url: 'http://localhost:4444',
            maxRetries: 3,
            inspectInterval: 1000,
            startDelay: 15000
        },
        options: {
            p: ['4444:4444'],
            shmSize: '2g'
        }
    },
    framework: 'mocha',
    reporters: ['spec',
        ['junit', {
            outputDir: './functional-xml-results/',
            outputFileFormat: function(opts) {
                return `results-${opts.capabilities.browserName}.${opts.capabilities.version}.${opts.capabilities.platform}.xml`;
            }
        }]
    ],
    mochaOpts: {
        ui: 'bdd',
        compilers: ['@babel/register'],
        timeout: 300000 // 5 minutes
    }
};
pipeline error: 
Execution of 1 spec files started at 2020-06-01T20:01:30.872Z
 2020-06-01T20:01:30.876Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "docker"
 2020-06-01T20:01:30.892Z INFO @wdio/cli:launcher: Run onPrepare hook
 2020-06-01T20:01:30.894Z DEBUG wdio-docker-service: Docker command: docker run --cidfile /builds/automation-wdio-docker/selenium_standalone_chrome_3_141_59_20200409.cid --rm -p 4444:4444 --shm-size 2g selenium/standalone-chrome:3.141.59-20200409
 2020-06-01T20:01:30.903Z WARN wdio-docker-service: Connecting dockerEventsListener: 70
 2020-06-01T20:01:30.906Z INFO wdio-docker-service: Cleaning up CID files
 2020-06-01T20:01:30.912Z WARN wdio-docker-service: NOTE: Pulling image for the first time. Please be patient.
 2020-06-01T20:01:30.920Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./automation/wdioDocker.config.js,--suite,accessibility
 2020-06-01T20:01:31.026Z ERROR wdio-docker-service: Error: Error executing sub-child: docker events --format "{{json .}}" --filter image=selenium/standalone-chrome:3.141.59-20200409
     at DockerEventsListener._onMessage (/builds/automation-wdio-docker/node_modules/wdio-docker-service/lib/utils/dockerEventsListener.js:67:21)
     at ChildProcess.emit (events.js:198:13)
     at ChildProcess.EventEmitter.emit (domain.js:448:20)
     at emit (internal/child_process.js:832:12)
     at process._tickCallback (internal/process/next_tick.js:63:19)
 2020-06-01T20:01:31.027Z WARN wdio-docker-service: Disconnecting dockerEventsListener: 70
 [0-0] 2020-06-01T20:01:31.441Z INFO @wdio/local-runner: Run worker command: run
 [0-0] RUNNING in chrome - /automation/accessibility/a11y-test.js
 [0-0] 2020-06-01T20:01:31.675Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "docker"
 [0-0] 2020-06-01T20:01:31.692Z DEBUG @wdio/local-runner:utils: init remote session
 [0-0] 2020-06-01T20:01:31.694Z INFO webdriverio: Initiate new session using the webdriver protocol
 [0-0] 2020-06-01T20:01:31.698Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
 [0-0] 2020-06-01T20:01:31.698Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
 [0-0] 2020-06-01T20:01:31.725Z INFO webdriver: Retrying 1/3
 2020-06-01T20:01:31.725Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
 2020-06-01T20:01:31.726Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
 [0-0] 2020-06-01T20:01:31.725Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4444
 [0-0] 2020-06-01T20:01:31.729Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4444
 [0-0] 2020-06-01T20:01:31.729Z INFO webdriver: Retrying 2/3
 2020-06-01T20:01:31.729Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
 [0-0] 2020-06-01T20:01:31.729Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
 [0-0] 2020-06-01T20:01:31.731Z INFO webdriver: Retrying 3/3
 2020-06-01T20:01:31.731Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
 [0-0] 2020-06-01T20:01:31.731Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4444
 [0-0] 2020-06-01T20:01:31.732Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
 [0-0] Error: Failed to create session.
 Unable to connect to "127.0.0.1:4444", make sure browser driver is running on that address.
 If you use services like chromedriver see initialiseServices logs above or in wdio.log file.
 [0-0] 2020-06-01T20:01:31.733Z ERROR webdriver: Request failed due to Error: connect ECONNREFUSED 127.0.0.1:4444
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
 2020-06-01T20:01:31.734Z ERROR webdriver: Error: connect ECONNREFUSED 127.0.0.1:4444
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
 [0-0] 2020-06-01T20:01:31.734Z ERROR @wdio/runner: Error: Failed to create session.
 Unable to connect to "127.0.0.1:4444", make sure browser driver is running on that address.
 If you use services like chromedriver see initialiseServices logs above or in wdio.log file.
     at startWebDriverSession (/builds/automation-wdio-docker/node_modules/webdriver/build/utils.js:45:11)
     at process._tickCallback (internal/process/next_tick.js:68:7)
 2020-06-01T20:01:31.845Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
 [0-0] FAILED in chrome - /automation/accessibility/a11y-test.js
 2020-06-01T20:01:31.846Z INFO @wdio/cli:launcher: Run onComplete hook
 2020-06-01T20:01:31.847Z INFO wdio-docker-service: Cleaning up CID files
 2020-06-01T20:01:31.847Z INFO wdio-docker-service: Docker container has stopped
 Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:00 
 2020-06-01T20:01:31.848Z INFO @wdio/local-runner: Shutting down spawned worker
 2020-06-01T20:01:32.101Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
 2020-06-01T20:01:32.101Z INFO @wdio/local-runner: shutting down

**Comment by stsvilik** [comment]
@shashtrih  I have updated the package to include error output of when sub-child process is running - this should help with debugging your current setup. This should appear as additional info in `Error: Error executing sub-child: ...` part

**Comment by shashtrih** [comment]
@stsvilik thanks for response. I have changed hostname to 'selenium__standalone-chrome' but i am getting different error that " request fauled due to getaddrinfo ENOTFOUND selenium__standalone-chrome selenium__standalone-chrome: 4444  , do you know what paraemeters i can use for hostname as i am running over ci/cd gitlab pipeline

**Comment by stsvilik** [comment]
@shashtrih Not all CI pipelines permit binding to an IP of the running node. You have to figure out how to obtain either IP or hostname of the node where docker is running, and use that as an address for selenium host.

**Comment by stsvilik** [comment]
@shashtrih Here is another idea for you. Since Gitlab supports docker executor, why not run `selenium/standalone-chrome:3.141.59-20200409` as one of them, and use Webdriver w/o any service at all, just point host to the selenium executor directly?

**Comment by stsvilik** [comment]
@shashtrih any updates on this, or should I close it?

**Comment by stsvilik** [comment]
Closing due to inactivity
